// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2F7vFtK9aFbIqR_0B4QIqrBHQbCEQrbo',
    appId: '1:298520442449:web:54380401b20d21a376aa70',
    messagingSenderId: '298520442449',
    projectId: 'payment-app-96',
    authDomain: 'payment-app-96.firebaseapp.com',
    storageBucket: 'payment-app-96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRLJC-pMw2thNDjR4-Jd9Ux7E005b59Zo',
    appId: '1:298520442449:android:a17b9a0d8695311876aa70',
    messagingSenderId: '298520442449',
    projectId: 'payment-app-96',
    storageBucket: 'payment-app-96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtykT1MY8RvNGJ9WkjhTNnD6AU4Yj7NVA',
    appId: '1:298520442449:ios:2ffbb480474f036b76aa70',
    messagingSenderId: '298520442449',
    projectId: 'payment-app-96',
    storageBucket: 'payment-app-96.appspot.com',
    iosClientId: '298520442449-6tdlji5scoqjsn1dnusg0j9ig4k8gjju.apps.googleusercontent.com',
    iosBundleId: 'com.example.roadfixTest',
  );
}
